### 1. Buscar todos os nomes (GET)
GET http://localhost:8080/api/pessoas

### 2. Recuperar por ID (GET) - Pegando o primeiro da lista
GET http://localhost:8080/api/pessoas/1

### 3. Salvar um novo nome (POST)
POST http://localhost:8080/api/pessoas
Content-Type: application/json

{
     "nome":"Jovennilton", 
     "dataNascimento":"1980-01-01", 
     "cpf":"11122233344", 
     "telefone":"(84)99999-0000", 
     "email":"joao@example.com"
}

### 4. Editar um nome existente (PUT) - Editando o índice 0 (João -> João Silva)
PUT http://localhost:8080/api/pessoas/1
Content-Type: application/json

{ 
    "nome":"João Silva", 
    "email":"novo@example.com" 
}
// após a edição, execute o passo 1 novamente para ver a atualização

### 5. Deletar um nome (DELETE) - Deletando o índice 1 (Maria)
DELETE http://localhost:8080/api/pessoas/1
// após a deleção, execute o passo 1 novamente para ver a lista atualizada